#
# Builds and runs all docker containers to start rankr
# @file docker-compose.yml

version: '3.3'
networks:
  backend:
  frontend:
services:
  apache:
    build: './system/apache'
    container_name: apache
    depends_on:
      - php
    networks:
      - backend
      - frontend
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    restart: always
    volumes:
      - ./system/apache/apache.conf:/usr/local/apache2/conf/vhosts/apache.conf
      - ./storage/src/:/usr/local/apache2/htdocs
  composer:
    image: composer:latest
    container_name: composer
    depends_on:
      - php
    environment:
      - COMPOSER_CACHE_DIR=/app/var/cache/composer
    volumes:
      - ./storage/:/app/
  php:
    build: './system/php'
    container_name: php
    networks:
      - backend
    restart: always
    volumes:
      - ./storage/:/var/www/html
  phpstan:
    image: ghcr.io/phpstan/phpstan
    container_name: phpstan
    volumes:
      - ./storage/:/app/
  phpunit:
    image: php:fpm-alpine
    container_name: php_unit
    depends_on:
      - composer
    entrypoint: vendor/bin/phpunit
    volumes:
      - ./storage/:/app/
    working_dir: /app
